### PR TITLE
Port glyphy-demo to Windows

### PR DESCRIPTION
**Pull request by tml1024**
You will need glew and freeglut to build and run it.

I have a VS solution for glyphy-demo, but did not commit that as I did
not bother to do it "properly", with different projects for the
library and the demo executable, Release and Debug configurations etc.

### CODE REVIEW

**Comment by behdad** [comment]
Ah, just found this again.  Let me take a look.

**Comment by behdad** [comment]
Looks great.  I'll give you write access, feel free to merge after addressing the minor issues.  Introducing demo_face_t can be done after you merge.

**Comment by behdad** [comment]
@tml1024 Ping?

**Comment by behdad** [comment]
@tml1024, ping!

**Comment by tml1024** [comment]
Sorry, have not had time to get back to GLyphy...

**Comment by leok7v** [comment]
Behdad,
I've finished what tml1024 started. Have a look: https://github.com/leok7v/glyphy
if you are still interested let me know.

**Comment by behdad** [comment]
Thanks @leok7v. Can you make a pull-request please?

**Comment by leok7v** [comment]
I am ashamed to admit I am green rookie in respect of pull requests. I was
out of github/git for almost 3 years stuck in dark ages of svn/Windows and
missed recent developments. Thus some small hand holding and advice on how
to proceed with pull requests would be much appreciated. Do I make pull
request on your repo or my clone of it? Do I merge into pull request commit
and don't push?

Sorry for being stupid/obsolete.

On Tuesday, June 7, 2016, Behdad Esfahbod <notifications@github.com> wrote:

> Thanks @leok7v <https://github.com/leok7v>. Can you make a pull-request
> please?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/behdad/glyphy/pull/12#issuecomment-224417519>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABGKBRNDi1ikX9yUKoWicZ8mr7VjgizOks5qJeAWgaJpZM4Ge_2S>
> .
>


-- 
Leo

**Comment by leok7v** [comment]
I think I've figured it out finally:
See: https://github.com/behdad/glyphy/pull/18

Leo

**Comment by ebraminio** [comment]
In favor of #19

**Comment by ebraminio** [comment]
I should say that #19 was never possible without your works guys, @tml1024 for originally his great work, and specially @leok7v which his works led me able to see glyphy on Windows for the first time, thanks a lot guys! Now that we have Windows support with a relatively lightweight solution with a CI, we can easier discuss needed further changes on it also. Thanks again.

**Pull request closed without merging**
